SAVE222/SAVE_BACKEND2

- src/main/java/com/save_backend/config/exception/BaseException.java
- src/main/java/com/save_backend/config/response/BaseResponse.java
- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
1. add
BaseResponse - json 응답 형식 지정
BaseResponseStatus - BaseResponse의 status 값 지정
BaseException - Exception 클래스를 상속받고 status 값을 지정할 수 있도록 함
2. modify - BaseResponseStatus
> modify - BaseResponseStatus

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/suspect/SuspectController.java
- src/main/java/com/save_backend/src/suspect/SuspectDao.java
- src/main/java/com/save_backend/src/suspect/SuspectProvider.java
- src/main/java/com/save_backend/src/suspect/SuspectService.java
- src/main/java/com/save_backend/src/suspect/model/GetSuspectRes.java
- src/main/java/com/save_backend/src/suspect/model/PostSuspectReq.java
- src/main/java/com/save_backend/src/suspect/model/PostSuspectRes.java
1. 학대의심자 정보 생성 API
Validation
1) 아동존재 여부
2) 필수값 입력 여부(성별, 나이, 아동과의 관계)
2. 학대의심자 정보 조회 API
> Sungyeon - 의심자 정보 생성, 조회 api

- .gitignore
- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/child/ChildController.java
- src/main/java/com/save_backend/src/child/ChildDao.java
- src/main/java/com/save_backend/src/child/ChildProvider.java
- src/main/java/com/save_backend/src/child/ChildService.java
- src/main/java/com/save_backend/src/child/model/GetChildInfoRes.java
- src/main/java/com/save_backend/src/child/model/PostChildReq.java
- src/main/java/com/save_backend/src/child/model/PostChildRes.java
1. child domain 생성
2. 아동 조회 api 생성
3. 아동 추가 api 생성
> add - get and create child

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/suspect/SuspectController.java
- src/main/java/com/save_backend/src/suspect/SuspectDao.java
- src/main/java/com/save_backend/src/suspect/SuspectProvider.java
- src/main/java/com/save_backend/src/suspect/SuspectService.java
- src/main/java/com/save_backend/src/suspect/model/GetSuspectRes.java
- src/main/java/com/save_backend/src/suspect/model/PatchSuspectReq.java
- src/main/java/com/save_backend/src/suspect/model/PatchSuspectRes.java
- src/main/java/com/save_backend/src/suspect/model/PostSuspectReq.java
- src/main/java/com/save_backend/src/suspect/model/PostSuspectRes.java
- 학대의심자 정보 수정 API 
-> 일단 patch method로 구현했습니다
- 학대의심자 정보 삭제 API : INACTIVE로 변경
- 학대의심자 존재여부, ACTIVE 상태 판단하는 validation 수정
> Sungyeon - 학대의심자 정보 수정, 삭제 API 구현

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/child/ChildController.java
- src/main/java/com/save_backend/src/child/ChildDao.java
- src/main/java/com/save_backend/src/child/ChildProvider.java
- src/main/java/com/save_backend/src/child/ChildService.java
- src/main/java/com/save_backend/src/child/model/PatchChildDelRes.java
- src/main/java/com/save_backend/src/child/model/PatchChildEditReq.java
- src/main/java/com/save_backend/src/child/model/PatchChildEditRes.java
- src/main/java/com/save_backend/src/child/model/PatchChildRes.java
1. 아동 정보 수정 api
2. 아동 정보 삭제 api
> add - 아동 정보 수정 및 삭제 api

- src/main/java/com/save_backend/src/user/UserController.java
- src/main/java/com/save_backend/src/user/UserDao.java
- src/main/java/com/save_backend/src/user/UserService.java
- src/main/java/com/save_backend/src/user/model/PutUserInfoReq.java
1. URI 수정
2. 유저 정보 수정 API에 PathVariable 추가
> modify - user URI 수정 및 PathVariable 추가

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/child/ChildController.java
- src/main/java/com/save_backend/src/child/ChildDao.java
1. where 조건에 active 추가
2. modifyPost -> modifyChild로 네이밍 변경
3. 코드 순서 변경
> modify - add validation status 'ACTIVE'

- src/main/java/com/save_backend/src/child/ChildController.java
- src/main/java/com/save_backend/src/child/ChildDao.java
- src/main/java/com/save_backend/src/child/ChildProvider.java
- src/main/java/com/save_backend/src/child/ChildService.java
> modify - add validation and comment

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/child/ChildController.java
- src/main/java/com/save_backend/src/suspect/SuspectController.java
필수값 validation
성별 유효값 validation
> add - essential data and valid gender data validation when creating and modifying

- src/main/java/com/save_backend/src/user/UserDao.java
- src/main/java/com/save_backend/src/user/UserProvider.java
- src/main/java/com/save_backend/src/user/UserService.java
- src/main/java/com/save_backend/src/utils/ValidationRegex.java
1. 본인의 이메일, 전화번호는 필터링하지 않게 수정하였습니다.
2. 삭제한 유저의 정보를 수정 불가능하도록 하였습니다.
3. 비밀번호의 길이를 8-20자 사이로 변경하였습니다.
> modify - 유저 수정, 삭제 및 비밀번호 길이 변경

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/child/ChildController.java
- src/main/java/com/save_backend/src/suspect/SuspectController.java
- src/main/java/com/save_backend/src/user/UserController.java
- src/main/java/com/save_backend/src/user/UserProvider.java
- src/main/java/com/save_backend/src/user/UserService.java
- src/main/resources/application.yml
https://www.notion.so/BaseResponseStatus-122ccefb34bb4860b4f5a05158cfe164
위 노션에 정리한대로 BaseResponseStatus 수정했습니다
application.yml 파일에 server : port : 9000 추가했습니다
> Sungyeon - BaseResponseStatus 수정

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/user/UserController.java
- src/main/java/com/save_backend/src/user/UserService.java
1. 회원가입 및 정보수정 시 이메일을 필수로 받던 사항을 선택으로 받을 수 있도록 변경
2. 변수 이름 수정
> modify - 이메일 값 선택 -> 필수, API의 baseResponseStatus 값 변경

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/user/UserProvider.java
2050, 2051번 - 수정
2052번 - 삭제
3040~3048 - 새로 추가
> modify - baseResponseStatus 수정

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/abuse/AbuseController.java
- src/main/java/com/save_backend/src/abuse/AbuseDao.java
- src/main/java/com/save_backend/src/abuse/AbuseProvider.java
- src/main/java/com/save_backend/src/abuse/AbuseService.java
- src/main/java/com/save_backend/src/abuse/model/GetAbuseRes.java
- src/main/java/com/save_backend/src/abuse/model/GetAbuseSuspectRes.java
- src/main/java/com/save_backend/src/abuse/model/PostAbuseReq.java
- src/main/java/com/save_backend/src/abuse/model/PostAbuseRes.java
- src/main/java/com/save_backend/src/abuse/model/PostAbuseSuspectReq.java
- src/main/java/com/save_backend/src/user/UserController.java
- src/main/java/com/save_backend/src/user/UserService.java
1. 정황 domain 생성
2. 정황 생성 api
3. 정황 조회 api
> 정황 생성 및 조회 api

- .gitignore
- build.gradle
- src/main/java/com/save_backend/config/s3/S3Config.java
- src/main/java/com/save_backend/src/media/S3Service.java
- src/main/java/com/save_backend/src/media/picture/PictureController.java
- src/main/java/com/save_backend/src/media/picture/PictureDao.java
- src/main/java/com/save_backend/src/media/picture/PictureDbRepository.java
- src/main/java/com/save_backend/src/media/picture/PictureService.java
- src/main/java/com/save_backend/src/media/picture/entity/Picture.java
- src/main/java/com/save_backend/src/media/picture/model/GetPictureRes.java
- src/main/java/com/save_backend/src/media/picture/model/PatchPictureRes.java
- src/main/java/com/save_backend/src/media/picture/model/PostPictureReq.java
- src/main/java/com/save_backend/src/media/picture/model/PostPictureRes.java
1. build.gradle 파일 수정
2. gitignore 파일에 s3 인증 관련 파일 추가
3. 사진 업로드, 다운로드, 삭제 API 생성
_(여러 시도를 해보았지만, 다운로드 API는 BaseResponse 형식으로 반환할 방법이 보이지 않아 관련 메소드는 일반적인 예외처리 형식을 따랐습니다.)_ -> url 반환으로 바꾸어 BaseResponse 형식으로 수정하였습니다.
> add - 사진 API 생성

- src/main/java/com/save_backend/src/media/recording/RecordingController.java
- src/main/java/com/save_backend/src/media/recording/RecordingDao.java
- src/main/java/com/save_backend/src/media/recording/RecordingDbRepository.java
- src/main/java/com/save_backend/src/media/recording/RecordingService.java
- src/main/java/com/save_backend/src/media/recording/entity/Recording.java
- src/main/java/com/save_backend/src/media/recording/model/GetRecordingRes.java
- src/main/java/com/save_backend/src/media/recording/model/PatchRecordingRes.java
- src/main/java/com/save_backend/src/media/recording/model/PostRecordingReq.java
- src/main/java/com/save_backend/src/media/recording/model/PostRecordingRes.java
조회 API에서 사진과 녹음파일 모두 url을 반환하지만, 사진과 달리 url을 통해 접근할 시 녹음파일이 다운로드 됩니다.
> add - 녹음파일 API 생성

- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/media/video/VideoController.java
- src/main/java/com/save_backend/src/media/video/VideoDao.java
- src/main/java/com/save_backend/src/media/video/VideoDbRepository.java
- src/main/java/com/save_backend/src/media/video/VideoService.java
- src/main/java/com/save_backend/src/media/video/entity/Video.java
- src/main/java/com/save_backend/src/media/video/model/GetVideoRes.java
- src/main/java/com/save_backend/src/media/video/model/PatchVideoRes.java
- src/main/java/com/save_backend/src/media/video/model/PostVideoReq.java
- src/main/java/com/save_backend/src/media/video/model/PostVideoRes.java
1. 동영상 API 생성
2. BaseResponse 수정 - 2200, 2300번대 코드 수정
> 동영상 API 생성, BaseResponse 수정

- src/main/java/com/save_backend/src/get/child/ChildListController.java
- src/main/java/com/save_backend/src/get/child/ChildListDao.java
- src/main/java/com/save_backend/src/get/child/ChildListProvider.java
- src/main/java/com/save_backend/src/get/child/model/GetChildListRes.java
- src/main/java/com/save_backend/src/get/suspect/SuspectListController.java
- src/main/java/com/save_backend/src/get/suspect/SuspectListDao.java
- src/main/java/com/save_backend/src/get/suspect/SuspectListProvider.java
- src/main/java/com/save_backend/src/get/suspect/model/GetSuspectListRes.java
1. 아동 리스트 조회 API
2. 학대의심자 리스트 조회 API
> add - 아동, 학대의심자 리스트 조회 API

- .gitignore
- build.gradle
- src/main/java/com/save_backend/config/redis/RedisConfig.java
- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/config/security/SecurityConfig.java
- src/main/java/com/save_backend/src/auth/AuthController.java
- src/main/java/com/save_backend/src/auth/AuthDao.java
- src/main/java/com/save_backend/src/auth/AuthProvider.java
- src/main/java/com/save_backend/src/auth/AuthService.java
- src/main/java/com/save_backend/src/auth/model/GetUserRes.java
- src/main/java/com/save_backend/src/auth/model/PostLoginReq.java
- src/main/java/com/save_backend/src/auth/model/PostLoginRes.java
- src/main/java/com/save_backend/src/auth/model/User.java
- src/main/java/com/save_backend/src/test/TestController.java
- src/main/java/com/save_backend/src/utils/jwt/JwtProperties.java
- src/main/java/com/save_backend/src/utils/jwt/JwtService.java
- src/main/resources/application.yml
1.  로그인  api  ( success -> jwt 토큰 발급)
2.  자동로그인 api (헤더의 token 검증)
3.  로그아웃 api (redis에 토큰 저장)
토큰과 redis를 이용한 테스트방법 
https://foregoing-yumberry-b7c.notion.site/redis-0e46dafa340b45e396a64dd0a17690ee
> Sungyeon - 로그인, 로그아웃 api

- build.gradle
- src/main/java/com/save_backend/config/response/BaseResponseStatus.java
- src/main/java/com/save_backend/src/auth/AuthController.java
- src/main/java/com/save_backend/src/auth/AuthDao.java
- src/main/java/com/save_backend/src/auth/AuthProvider.java
- src/main/java/com/save_backend/src/auth/AuthService.java
- src/main/java/com/save_backend/src/auth/model/GetTempPasswordRes.java
- src/main/java/com/save_backend/src/auth/model/PatchAuthReq.java
- src/main/java/com/save_backend/src/auth/model/PatchAuthRes.java
- src/main/java/com/save_backend/src/utils/jwt/JwtService.java
- src/main/java/com/save_backend/src/utils/mail/MailDTO.java
- src/main/java/com/save_backend/src/utils/mail/MailService.java
- src/main/resources/application.yml
1. 비밀번호 수정 api
2. 비밀번호 찾기 api
3. jwt 관련 validation 코드 리팩토링
*테스트 하시려면 yml 파일에 mail - password 입력하셔야 돼요!
> Sungyeon - 비밀번호 수정, 비밀번호 찾기 api

- src/main/java/com/save_backend/src/abuse/AbuseDao.java
학대 정확 삭제시 관련 사진, 동영상, 녹음파일  status 를 'INACTIVE' 처리
> mod - delete picture, video, recording about abuse idx

- .gitignore
- src/main/java/com/save_backend/src/get/child/ChildListDao.java
- src/main/java/com/save_backend/src/get/child/model/GetChildListRes.java
- src/main/java/com/save_backend/src/get/suspect/SuspectListDao.java
- src/main/java/com/save_backend/src/get/suspect/model/GetSuspectListRes.java
1. 아동 리스트 조회 API - 생성 날짜, 상세 주소 추가
2. 학대 의심자 리스트 조회 API - 상세 주소 추가
3. .gitignore 파일 수정
> modify - 리스트 API, gitignore 수정

- src/main/java/com/save_backend/src/abuse/AbuseDao.java
- src/main/java/com/save_backend/src/abuse/model/GetAbuseRecRes.java
- src/main/java/com/save_backend/src/abuse/model/GetAbuseRes.java
1. GetAbuseRecRes에서 녹음 파일 이름 추가
2. AbuseDao 중 getAbuseByIdx 메소드에서 QueryForObject으로 받아야하는 getAbuseSuspect를 외부 메소드로 분리 -> 예외 처리 목적
> modify - 학대 정황 조회 API 수정

- src/main/java/com/save_backend/src/get/abuse/AbuseListController.java
- src/main/java/com/save_backend/src/get/abuse/AbuseListDao.java
- src/main/java/com/save_backend/src/get/abuse/AbuseListProvider.java
- src/main/java/com/save_backend/src/get/abuse/model/GetAbuseListRes.java
childIdx로 학대정황 리스트 조회하는 api 추가
> add - add getAbuseList

- src/main/java/com/save_backend/src/abuse/AbuseDao.java
- src/main/java/com/save_backend/src/abuse/model/GetAbuseRes.java
- src/main/java/com/save_backend/src/abuse/model/GetAbuseSuspectRes.java
- src/main/java/com/save_backend/src/get/abuse/AbuseListDao.java
- src/main/java/com/save_backend/src/get/abuse/model/GetAbuseListRes.java
학대정황 리스트 조회 생성날짜 데이터타입 String에서 Date로 변경
학대정황 생성날짜 데이터타입 String에서 Date로 변경
학대정황 의심자 조회 상세주소, 관계 추가
> modify create_date String to Date
